# Generated by Django 6.1.1 on 2026-09-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=20)),
                ('editora', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('disponiveis', models.IntegerField(default=1)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
