# Generated by Django 6.1.1 on 2026-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='disponiveis',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
