# Generated by Django 6.1.1 on 2026-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Central', '0002_alter_livro_disponiveis_alter_livro_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do livro'),
        ),
    ]
