# Generated by Django 6.1.1 on 2026-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Central', '0005_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('Emprestado', 'Emprestado'), ('Devolvido', 'Devolvido')], default='Emprestado', max_length=20),
        ),
    ]
